In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
from google.colab import files
uploaded = files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


In [3]:
import io

In [4]:
df = pd.read_csv(io.BytesIO(uploaded['Social_Network_Ads.csv']))

In [5]:
print(df)

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]


In [9]:
print("Number of rows is = ", df.shape[0], " \nNumber of columns is =	"	, df.shape[1])

Number of rows is =  400  
Number of columns is =	 3


In [11]:
df.columns

Index(['Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [12]:
df.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [13]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [15]:
correlation = pd.DataFrame(df.corr().Purchased) 
correlation

Purchased
Age               0.622454
EstimatedSalary   0.362083
Purchased         1.000000

In [17]:
df.drop('Age', axis = 1, inplace=True) 

In [18]:
df['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [22]:
pd.crosstab(df.EstimatedSalary,df.Purchased,normalize = "index")

Purchased          0    1
EstimatedSalary          
15000            1.0  0.0
16000            1.0  0.0
17000            1.0  0.0
18000            1.0  0.0
19000            1.0  0.0
...              ...  ...
146000           0.0  1.0
147000           0.0  1.0
148000           0.0  1.0
149000           0.0  1.0
150000           0.0  1.0

[117 rows x 2 columns]

In [23]:
X = df.drop(['Purchased'],axis = 1) 
y = df['Purchased']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [26]:
from sklearn.preprocessing import StandardScaler

In [28]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train) 
X_test = sc_X.transform(X_test)


In [29]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, solver='lbfgs' ) 
classifier.fit(X_train, y_train)


LogisticRegression(random_state=0)

In [30]:
y_pred = classifier.predict(X_test)

In [31]:
print(X_test[:10]) 
print('-'*15)
print(y_pred[:10])


[[ 0.50496393]
 [-0.5677824 ]
 [ 0.1570462 ]
 [ 0.27301877]
 [-0.5677824 ]
 [-1.43757673]
 [-1.58254245]
 [ 2.15757314]
 [-0.04590581]
 [-0.77073441]]
---------------
[0 0 0 0 0 0 0 1 0 0]


In [32]:
print(y_pred[:20])

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0]


In [33]:
print(y_test[:20])

132    0
309    0
341    0
196    0
246    0
60     0
155    0
261    1
141    0
214    0
37     0
134    0
113    0
348    0
12     0
59     0
293    0
140    0
206    1
199    0
Name: Purchased, dtype: int64


In [34]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred) 
print(cm)

[[66  2]
 [17 15]]


In [35]:
from sklearn import metrics 
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.97      0.87        68
           1       0.88      0.47      0.61        32

    accuracy                           0.81       100
   macro avg       0.84      0.72      0.74       100
weighted avg       0.82      0.81      0.79       100

